---
- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:
    - name: Network Getting Started First Playbook
    ios_command:
    commands: show run
